package PanelPackage;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author mohammad
 */
public class Login extends JPanel {

    /**
     * Creates new form NewJPanel
     */
    ImageIcon i = new ImageIcon("src\\image.jpg");

    public Login() {
        initComponents();
        jPanel1.setBackground(new Color(0, 0, 0, 75));
        LoginButton.setBackground(new Color(255, 255, 255));
        signUpButton.setBackground(new Color(255, 255, 255));
        centerPanel();
        addPlaceholders();
        signUpButton.setFont(new Font("Segoe UI", Font.PLAIN + Font.BOLD + Font.ITALIC, 14));
        LoginButton.setFont(new Font("Segoe UI", Font.PLAIN + Font.BOLD + Font.ITALIC, 14));
        jLabel1.setFont(new Font("Segoe UI", Font.PLAIN + Font.BOLD + Font.ITALIC, 14));
    //    showPassChec.setFont(new Font("Segoe UI", Font.PLAIN + Font.BOLD + Font.ITALIC, 14));
      //  showPassChec.setForeground(Color.WHITE);
        //showPassChec.setBackground(new Color(0,0,0,0));
        jLabel1.setForeground(Color.WHITE);
       
    }

    private void addPlaceholders() {

        addPlaceholder(Email, "Enter your Email");
        addPlaceholder(password, "Enter your Password");
    }

    private void addPlaceholder(javax.swing.JTextField textField, String placeholder) {
        textField.setForeground(Color.GRAY);
        if (textField instanceof JPasswordField) {
            password.setEchoChar('\u0000');
        }
        textField.setText(placeholder);

        textField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setForeground(Color.GRAY);
                    textField.setText(placeholder);
                }
            }
        });
    }

    private void centerPanel() {
        // Use GridBagLayout for centering
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        add(jPanel1, gbc);
    }

    @Override
    protected void paintComponent(Graphics g) {
        g.drawImage(i.getImage(), 0, 0, this.getWidth(), this.getHeight(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
       // showPassChec = new javax.swing.JCheckBox();
        signUpButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        Email.setToolTipText("");

        password.setName("password"); // NOI18N
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        LoginButton.setText("Login");
//        LoginButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                LoginButtonActionPerformed(evt);
//            }
//        });
//
//        showPassChec.setText("show password");
//        showPassChec.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                showPassChecActionPerformed(evt);
//            }
//        });

        signUpButton.setText("Sign Up");
        

        jLabel1.setText("New member?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
                                                                Short.MAX_VALUE)
                                                        .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                400, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(182, 182, 182)
                                                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(106, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(signUpButton))
                                        //.addComponent(showPassChec))
                                .addGap(41, 41, 41)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                //.addComponent(showPassChec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LoginButton)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(signUpButton)
                                        .addComponent(jLabel1))
                                .addGap(0, 9, Short.MAX_VALUE)));

        Email.getAccessibleContext().setAccessibleDescription("username");
        password.getAccessibleContext().setAccessibleName("");
        password.getAccessibleContext().setAccessibleDescription("password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(131, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(218, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)));
    }// </editor-fold>//GEN-END:initComponents

//    private void showPassChecActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showPassChecActionPerformed
//        // TODO add your handling code here:
//        if (showPassChec.isSelected()) {
//            password.setEchoChar('\u0000');
//        } else {
//            password.setEchoChar('*');
//        }
//    }// GEN-LAST:event_showPassChecActionPerformed

//    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LoginButtonActionPerformed
//        // TODO add your handling code here:
//        if (Email.getText().equals("Enter your Email")) {
//            Email.setForeground(Color.BLACK);
//        }
//        if (password.getText().equals("Enter your Password")) {
//            password.setForeground(Color.BLACK);
//
//        }
//    }// GEN-LAST:event_LoginButtonActionPerformed

//    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_passwordKeyTyped
//        // TODO add your handling code here:
//    	 if (showPassChec.isSelected()) {
//             password.setEchoChar('\u0000');
//         } else {
//             password.setEchoChar('*');
//         }
//    }// GEN-LAST:event_passwordKeyTyped
    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // TODO add your handling code here:
        password.setEchoChar('*');
    }//GEN-LAST:event_passwordKeyTyped
    public String getEmail() {
        return Email.getText();
    }

    public String getPassword() {
        return password.getText();
    }

    public JButton getLoginButton() {
        return LoginButton;
    }
    public JButton getSignUpButton() {
    	return signUpButton;
    }
    public JPanel getPanel() {
    	return jPanel1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
  //  private javax.swing.JCheckBox showPassChec;
    private javax.swing.JButton signUpButton;
    // End of variables declaration//GEN-END:variables
    
    
}
