package PanelPackage;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
//package EnglishProject;

import java.awt.*;
import java.awt.event.*;
import java.util.regex.*;
import javax.swing.*;

/**
 *
 * @author mohammad
 */
public class SignUp extends javax.swing.JPanel {

    /**
     * Creates new form SignUp
     */
      ImageIcon i = new ImageIcon("image.jpg");

    public SignUp() {
        initComponents();
         jPanel1.setBackground(new Color(0,0,0,75));
         LoginButton.setBackground(new Color(255,255,255));
         signUpButton.setBackground(new Color(255,255,255));
         centerPanel();
          addPlaceholders();
         signUpButton.setFont(new Font("Segoe UI",Font.PLAIN+Font.BOLD+Font.ITALIC,14));
         jLabel1.setForeground(Color.WHITE);
        LoginButton.setFont(new Font("Segoe UI",Font.PLAIN+Font.BOLD+Font.ITALIC,14));
        jLabel1.setFont(new Font("Segoe UI",Font.PLAIN+Font.BOLD+Font.ITALIC,14));
     //   showPassChec.setFont(new Font("Segoe UI",Font.PLAIN+Font.BOLD+Font.ITALIC,14));
       // showPassChec.setForeground(Color.WHITE);
    }
       private void addPlaceholders() {
       
        addPlaceholder(username, "Enter your Full Name");
        addPlaceholder(password, "Enter your Password");
        addPlaceholder(Email, "Enter your Email");
    }
private void addPlaceholder(javax.swing.JTextField textField, String placeholder) {
        textField.setForeground(Color.GRAY);
        if(textField instanceof  JPasswordField)
        {
            password.setEchoChar('\u0000');
        }
        textField.setText(placeholder);

        textField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setForeground(Color.GRAY);
                    textField.setText(placeholder);
                    
                }
              
            }
        });
    }
    private void centerPanel() {
        // Use GridBagLayout for centering
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        add(jPanel1, gbc);
    }
    
   
    @Override
  protected void paintComponent(Graphics g) {
    g.drawImage(i.getImage(), 0, 0, this.getWidth(), this.getHeight(), this);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        signUpButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
     //   showPassChec = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign up", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        username.setToolTipText("");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
        });

        password.setName("password"); // NOI18N
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        signUpButton.setText("Sign Up");
//        signUpButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                signUpButtonActionPerformed(evt);
//            }
//        });

        LoginButton.setText("Login");
        

       // showPassChec.setText("show password");
       // showPassChec.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                //showPassChecActionPerformed(evt);
//            }
//        });

        jLabel1.setText("Already a member?");

        Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   // .addComponent(showPassChec)
                    .addComponent(LoginButton))
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                //.addComponent(showPassChec)
                .addGap(10, 10, 10)
                .addComponent(signUpButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

//    private void showPassChecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassChecActionPerformed
//        // TODO add your handling code here:
//             if(showPassChec.isSelected()){
//            password.setEchoChar('\u0000');
//          }
//        else{
//            password.setEchoChar('*');
//            showPassChec.setText("Show password");
//        }
//    }//GEN-LAST:event_showPassChecActionPerformed

//    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
//        // TODO add your handling code here:
//        char[] pass=password.getPassword();
//        int len=pass.length;
//        if(username.getText().equals("Enter your Full Name")){
//            username.setForeground(Color.BLACK);
//        }
//        if (isValidEmail(Email.getText())) {
//        Email.setText("Vailed Email");
//        } 
//        else if(!isValidEmail(Email.getText()) || Email.getText().equals("")) {
//             Email.setForeground(Color.BLACK);
//                  Email.setText("Not a Vailed Email");
//                 
//               }
//        if(len<=8 || password.getText().equals("Enter your Password")){
//            password.setForeground(Color.BLACK);
//            password.setText("Enter a password greater than 8 characters");
//            
//        }
        
        
    //}GEN-LAST:event_signUpButtonActionPerformed

    private void EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailFocusGained
        // TODO add your handling code here:
        if(Email.getText().equals("Not a Vailed Email")){
            Email.setText("");
            Email.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_EmailFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if(password.getText().equals("Enter a password greater than 8 characters")){
            password.setText("");
            password.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_passwordFocusGained

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
         if(username.getText().equals("Enter your full Name")){
            username.setText("");
            username.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_usernameFocusGained

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // TODO add your handling code here:
        password.setEchoChar('*');
    }//GEN-LAST:event_passwordKeyTyped
    public String getUsername(){
    return username.getText();
}
    public String getEmail(){
    return Email.getText();
}
    public String getPassword(){
        return password.getText();
    }
    public JButton getSignUpButton(){
    return signUpButton;
}
    public JButton getLogInButton() {
    	return LoginButton;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
  //  private javax.swing.JCheckBox showPassChec;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

  
}
